services:
  stats-server:
    build: stats/stat-server
    image: stat-server-image
    container_name: stat-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=db_admin
      - SPRING_DATASOURCE_PASSWORD=AbRaKaDaBrA
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver


  stats-db:
    image: postgres:16.1
    container_name: stat-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=AbRaKaDaBrA
      - POSTGRES_USER=db_admin
      - POSTGRES_DB=stats

  ewm-service:
    build: main-service
    image: main-server-image
    container_name: main-server-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=db_admin
      - SPRING_DATASOURCE_PASSWORD=AbRaKaDaBrA
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=AbRaKaDaBrA